
package Planilla;

/**
 *
 * @author 
 */
public class frmCrearPlanilla extends javax.swing.JFrame {

    /**
     * Creates new form frmCrearPlanilla
     */
    public frmCrearPlanilla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panCuerpo = new javax.swing.JPanel();
        lblAgregarBus = new javax.swing.JLabel();
        lblAgregarChofer = new javax.swing.JLabel();
        lblAgregarViaje = new javax.swing.JLabel();
        boxBuses = new javax.swing.JComboBox<>();
        boxChoferes = new javax.swing.JComboBox<>();
        boxViajes = new javax.swing.JComboBox<>();
        panMantenimiento = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnCrearPlanilla = new javax.swing.JButton();
        btnReservarPasajes = new javax.swing.JButton();
        btnImprimirPlanilla = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAgregarBus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAgregarBus.setText("AGREGAR CAMION");

        lblAgregarChofer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAgregarChofer.setText("AGREGAR CHOFER");

        lblAgregarViaje.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAgregarViaje.setText("AGREGAR VIAJE");

        boxBuses.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxBuses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VACÍO" }));
        boxBuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxBusesActionPerformed(evt);
            }
        });

        boxChoferes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxChoferes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VACÍO" }));
        boxChoferes.setToolTipText("");

        boxViajes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxViajes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VACÍO" }));

        javax.swing.GroupLayout panCuerpoLayout = new javax.swing.GroupLayout(panCuerpo);
        panCuerpo.setLayout(panCuerpoLayout);
        panCuerpoLayout.setHorizontalGroup(
            panCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAgregarBus)
                    .addComponent(lblAgregarViaje)
                    .addComponent(lblAgregarChofer)
                    .addComponent(boxBuses, 0, 212, Short.MAX_VALUE)
                    .addComponent(boxChoferes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boxViajes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panCuerpoLayout.setVerticalGroup(
            panCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAgregarBus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxBuses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAgregarChofer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxChoferes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAgregarViaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxViajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        boxBuses.setFocusable(false);
        boxChoferes.setFocusable(false);
        boxViajes.setFocusable(false);

        getContentPane().add(panCuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSalir.setText("Salir");

        btnCrearPlanilla.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCrearPlanilla.setText("Crear Planilla");

        btnReservarPasajes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnReservarPasajes.setText("Reservar Pasajes");

        btnImprimirPlanilla.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnImprimirPlanilla.setText("Imprimir Planilla");

        javax.swing.GroupLayout panMantenimientoLayout = new javax.swing.GroupLayout(panMantenimiento);
        panMantenimiento.setLayout(panMantenimientoLayout);
        panMantenimientoLayout.setHorizontalGroup(
            panMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMantenimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir)
                    .addComponent(btnCrearPlanilla)
                    .addComponent(btnReservarPasajes)
                    .addComponent(btnImprimirPlanilla))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panMantenimientoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCrearPlanilla, btnImprimirPlanilla, btnReservarPasajes, btnSalir});

        panMantenimientoLayout.setVerticalGroup(
            panMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMantenimientoLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(btnCrearPlanilla)
                .addGap(18, 18, 18)
                .addComponent(btnReservarPasajes)
                .addGap(18, 18, 18)
                .addComponent(btnImprimirPlanilla)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        btnSalir.setFocusPainted(false);
        btnCrearPlanilla.setFocusPainted(false);
        btnReservarPasajes.setFocusPainted(false);
        btnImprimirPlanilla.setFocusPainted(false);

        getContentPane().add(panMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PLANILLA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 620, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxBusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxBusesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxBusesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCrearPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCrearPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCrearPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCrearPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCrearPlanilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> boxBuses;
    public javax.swing.JComboBox<String> boxChoferes;
    public javax.swing.JComboBox<String> boxViajes;
    public javax.swing.JButton btnCrearPlanilla;
    public javax.swing.JButton btnImprimirPlanilla;
    public javax.swing.JButton btnReservarPasajes;
    public javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAgregarBus;
    private javax.swing.JLabel lblAgregarChofer;
    private javax.swing.JLabel lblAgregarViaje;
    private javax.swing.JPanel panCuerpo;
    private javax.swing.JPanel panMantenimiento;
    // End of variables declaration//GEN-END:variables
}
