/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package agenciaCamiones;

/**
 *
 * @author D&J GODS PC
 */
public class frmAgenciaCamiones extends javax.swing.JFrame {

    /** Creates new form frmAgenciaBuses */
    public frmAgenciaCamiones() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        btnCamiones = new javax.swing.JButton();
        btnPlanillas = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        btnViajes = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnConductores = new javax.swing.JButton();
        btnCargas = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCamiones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCamiones.setText("Camiones");
        getContentPane().add(btnCamiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 120, -1));
        btnCamiones.setFocusPainted(false);

        btnPlanillas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPlanillas.setText("Planillas");
        getContentPane().add(btnPlanillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 120, -1));
        btnPlanillas.setFocusPainted(false);

        btnConsultas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnConsultas.setText("Consultas");
        getContentPane().add(btnConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 120, -1));
        btnConsultas.setFocusPainted(false);

        btnViajes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnViajes.setText("Viajes");
        getContentPane().add(btnViajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 120, -1));
        btnViajes.setFocusPainted(false);

        btnClientes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, -1));
        btnClientes.setFocusPainted(false);

        btnConductores.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnConductores.setText("Conductores");
        getContentPane().add(btnConductores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 120, -1));
        btnConductores.setFocusPainted(false);

        btnCargas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCargas.setText("Cargas");
        getContentPane().add(btnCargas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 120, -1));
        btnCargas.setFocusPainted(false);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 80, 80));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("WCC & M S.A.C.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 620, 50));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("EMPRESA DE TRANSPORTES ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAgenciaCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAgenciaCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAgenciaCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAgenciaCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAgenciaCamiones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCamiones;
    public javax.swing.JButton btnCargas;
    public javax.swing.JButton btnClientes;
    public javax.swing.JButton btnConductores;
    public javax.swing.JButton btnConsultas;
    public javax.swing.JButton btnPlanillas;
    private javax.swing.JButton btnSalir;
    public javax.swing.JButton btnViajes;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
