
package Cliente;

/**
 *
 * @author 
 */
public class frmClienteEliminar extends javax.swing.JFrame {

    /**
     * Creates new form frmCliente
     */
    public frmClienteEliminar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panEliminar = new javax.swing.JPanel();
        lblBuscarCliente = new javax.swing.JLabel();
        lblDniBuscar = new javax.swing.JLabel();
        txtDniBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblApellidoPaterno = new javax.swing.JLabel();
        lblApellidoMaterno = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblRuc = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblClienteNombre = new javax.swing.JLabel();
        lblClienteApellidoPaterno = new javax.swing.JLabel();
        lblClienteApellidoMaterno = new javax.swing.JLabel();
        lblClienteDni = new javax.swing.JLabel();
        lblClienteTelefono = new javax.swing.JLabel();
        lblClienteRuc = new javax.swing.JLabel();
        lblClienteDireccion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscarCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblBuscarCliente.setText("Buscar cliente:");

        lblDniBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDniBuscar.setText("Ingrese Dni:");

        txtDniBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBuscar.setText("Buscar");

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNombre.setText("Nombre:");

        lblApellidoPaterno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblApellidoPaterno.setText("Apellido Paterno:");

        lblApellidoMaterno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblApellidoMaterno.setText("Apellido Materno:");

        lblDni.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDni.setText("DNI:");

        lblTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTelefono.setText("Teléfono:");

        lblRuc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblRuc.setText("RUC:");

        lblDireccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDireccion.setText("Dirección:");

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEliminar.setText("Eliminar");

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");

        lblClienteNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblClienteNombre.setText("Nombre");

        lblClienteApellidoPaterno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblClienteApellidoPaterno.setText("ApellidoP");

        lblClienteApellidoMaterno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblClienteApellidoMaterno.setText("ApellidoM");

        lblClienteDni.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblClienteDni.setText("Dni");

        lblClienteTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblClienteTelefono.setText("Teléfono");

        lblClienteRuc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblClienteRuc.setText("RUC");

        lblClienteDireccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblClienteDireccion.setText("Dirección");

        javax.swing.GroupLayout panEliminarLayout = new javax.swing.GroupLayout(panEliminar);
        panEliminar.setLayout(panEliminarLayout);
        panEliminarLayout.setHorizontalGroup(
            panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBuscarCliente)
                    .addGroup(panEliminarLayout.createSequentialGroup()
                        .addGroup(panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panEliminarLayout.createSequentialGroup()
                                .addComponent(lblDireccion)
                                .addGap(255, 255, 255))
                            .addGroup(panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panEliminarLayout.createSequentialGroup()
                                    .addComponent(lblRuc)
                                    .addGap(282, 282, 282))
                                .addComponent(lblTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panEliminarLayout.createSequentialGroup()
                                    .addComponent(lblNombre)
                                    .addGap(66, 66, 66)
                                    .addComponent(lblClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panEliminarLayout.createSequentialGroup()
                                    .addComponent(lblApellidoPaterno)
                                    .addGap(20, 20, 20)
                                    .addComponent(lblClienteApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panEliminarLayout.createSequentialGroup()
                                    .addGroup(panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblApellidoMaterno)
                                        .addComponent(lblDni))
                                    .addGap(18, 18, 18)
                                    .addGroup(panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblClienteDni, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblClienteApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblClienteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblClienteRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblClienteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(24, 24, 24)
                        .addGroup(panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminar)
                            .addComponent(btnCancelar)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panEliminarLayout.createSequentialGroup()
                        .addComponent(lblDniBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(txtDniBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panEliminarLayout.setVerticalGroup(
            panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscarCliente)
                .addGap(18, 18, 18)
                .addGroup(panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDniBuscar)
                    .addComponent(txtDniBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblClienteNombre))
                .addGap(18, 18, 18)
                .addGroup(panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoPaterno)
                    .addComponent(lblClienteApellidoPaterno)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addGroup(panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoMaterno)
                    .addComponent(lblClienteApellidoMaterno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDni)
                        .addComponent(lblClienteDni)))
                .addGap(18, 18, 18)
                .addGroup(panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(lblClienteTelefono))
                .addGap(18, 18, 18)
                .addGroup(panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRuc)
                    .addComponent(lblClienteRuc))
                .addGap(18, 18, 18)
                .addGroup(panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(lblClienteDireccion))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnBuscar.setFocusPainted(false);
        btnEliminar.setFocusPainted(false);
        btnCancelar.setFocusPainted(false);

        getContentPane().add(panEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 458, 320));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ELIMINAR CLIENTE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 620, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClienteEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClienteEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClienteEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClienteEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmClienteEliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblApellidoMaterno;
    private javax.swing.JLabel lblApellidoPaterno;
    private javax.swing.JLabel lblBuscarCliente;
    public javax.swing.JLabel lblClienteApellidoMaterno;
    public javax.swing.JLabel lblClienteApellidoPaterno;
    public javax.swing.JLabel lblClienteDireccion;
    public javax.swing.JLabel lblClienteDni;
    public javax.swing.JLabel lblClienteNombre;
    public javax.swing.JLabel lblClienteRuc;
    public javax.swing.JLabel lblClienteTelefono;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblDniBuscar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRuc;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JPanel panEliminar;
    public javax.swing.JTextField txtDniBuscar;
    // End of variables declaration//GEN-END:variables
}
